name: uv lock check

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: hbelmiro/uv-lock-check@5e383ca4a558c5c8b39c577601d7c71e7d9290dd # v0.3.0
