name: uv lock check

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hbelmiro/uv-lock-check@5e383ca4a558c5c8b39c577601d7c71e7d9290dd # v0.3.0
